language: cpp

deploy:
  provider: releases
  api_key:
    secure: 0FQRtVSqKYui5GzEBrv+OWwnJG59roRreBsWy+/7VOlelRVGHFT+Onj5cDz3tmd94lFCV6DjdRkv6D4csx6TFX9E5FzuTzBb0FPhSYrpZDB5wMebuJXEVy5kA4yq856YgD+w91vBRlaqcF8JDVaNe/1jHG4piEI3wOa0inkmqu3z8QdcRz5tsEGfNN6DIiNYQL1czrx5UGzNHxZlMdHmFy+Zn8yH8wfJtS0szflXAqAvQPns4AqfqycZpb61EDXpy0qJh2CSpleZLnybez9heBdFsWH9lNwdbWRlR9tKiK5IR+A4PMPvuzzUaOQ8HWgGewiNtn9ednyp4HSLwkEmn4J67j9fG/eLYu+OyUnQ9teX0U3RsFNTs0NdX43NCRK1eiwsf11SBfz0gI+a1Y/re0AcUx+6BL2CGOdn7Nnu9O9vhHEd2vNKAWNzceiBNei0OsVes8bC9QLti7+wj6MQWkk9QDqRHK6UGnBz0keJcqVMX8kp1EIxX0a/4WtGOLBIXuS9v1w3jckD85dG88BIrIT9SP+fqceAiUiu6D94axG7U5iNXrnBrTb6kuAWrJQE2Z5y1Ihc1ep5AZqS3rcqNyyaoBg8tUpFp0Mm3WdyYxT6XBkCIPkHQ9f6SuPYj5ricMiFEwL9ChKzjuCWpOy2NLIeXu2GRseF56E3kAmiKZU=
  skip_cleanup: true
  file_glob: true
  file: dist/*
  on:
    tags: true

matrix:
  include:
    - os: linux
      env: PLATFORM=linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-6
            - gcc-6
            - cmake
            - cmake-data
            - libx11-xcb-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxcb-image0-dev
            - libxcb-randr0-dev
            - libudev-dev
            - libopenal-dev
            - freeglut3-dev
            - libjpeg-dev
            - libfreetype6-dev
            - libxrandr-dev
            - libglew-dev
            - libsndfile1-dev
            - libasound2-dev
            - alsa-utils
            - alsa-oss
      script: ./bin/build_unix.sh
      before_deploy: ./bin/archive_unix.sh
    - os: linux
      language: android
      env: PLATFORM=android
      addons:
        apt:
          packages:
            - autogen
            - autoconf
            - automake
            - libtool
            - pkg-config
            - ninja-build
      android:
        components:
          - tools
          - platform-tools
          - tools # it's required to have this duplicated

          - build-tools-25.0.2
          - android-21
        licenses:
          - '.+'
      before_install:
        - rm -fr ./android-ndk-r16b
        - curl -L http://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip -O
        - unzip -oq android-ndk-r15c-linux-x86_64.zip
        - rm android-ndk-r15c-linux-x86_64.zip
        - export ANDROID_NDK_HOME=`pwd`/android-ndk-r15c
        - export ANDROID_TOOLCHAIN_HOME=`pwd`
        - export ANDROID_NDK_VER=r15c
      install:
        - "yes | sdkmanager ndk-bundle"
        - "yes | sdkmanager \"extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2\""
      script: ./bin/build_android.sh
      before_deploy: ./bin/archive_android.sh
    - os: osx
      env: PLATFORM=osx
      compiler: clang
      before_install:
        - brew update
        - brew install libsndfile
      script: ./bin/build_unix.sh
      before_deploy: ./bin/archive_unix.sh
